name: PR Build, test and package if approved

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check secrets
        run: |
          if [ -n "$FOO" ]; then
            echo "FOO secret is set"
          else
            echo "FOO secret is NOT set"
          fi
        env:
          FOO: ${{ secrets.FOO }}

  test-package:
    runs-on: ubuntu-latest
    # Only run if the comment is on a PR, contains '/ok-to-test', and was posted by a maintainer
    if: >
      github.event.issue.pull_request != null &&
      startsWith(github.event.comment.body, '/ok-to-test') &&
      contains(fromJSON('["MEMBER", "OWNER", "COLLABORATOR"]'), github.event.comment.author_association)
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check secrets
        run: |
          if [ -n "$FOO" ]; then
            echo "FOO secret is set"
          else
            echo "FOO secret is NOT set"
          fi
        env:
          FOO: ${{ secrets.FOO }}

      - name: Run tests
        run: mvn test

      - name: Run package
        run: mvn package
